env: default

spring:
  application:
    name: Demo
  profiles:
    active: gdev
  boot:
    admin.client:
      instance:
        prefer-ip: true
      url: http://localhost:8400
      username: admin
      password: admin
  jackson.serialization:
    write-dates-as-timestamps: true
    write_date_timestamps_as_nanoseconds: false


async:
  core-pool-size: 10
  max-pool-size: 50
  queue-capacity: 1000