env: default

server:
    port: 8080

spring:
    application:
        name: pirsp_prtal
    profiles:
        active:
         - gdev # 激活gdev
    # 配置数据源，使用阿里巴巴的druid数据库连接池
    druid:
        initial-size: 1
        min-idle: 1
        max-active: 20
        test-on-borrow: true
        stat-view-servlet:
            allow: true

async:
    core-pool-size: 2
    max-pool-size: 50
    queue-capacity: 10000