env: default

spring:
  application:
    name: amt
  profiles:
    active: gdev
  boot:
    admin.client:
      url: http://localhost:8403
      username: admin
      password: admin
  jackson.serialization:
    write-dates-as-timestamps: true
    write_date_timestamps_as_nanoseconds: false